// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "advanced/demo-mode.mdx": () => import("../content/docs/advanced/demo-mode.mdx?collection=docs"), "advanced/keyboard-shortcuts.mdx": () => import("../content/docs/advanced/keyboard-shortcuts.mdx?collection=docs"), "advanced/multi-bridge.mdx": () => import("../content/docs/advanced/multi-bridge.mdx?collection=docs"), "advanced/organization.mdx": () => import("../content/docs/advanced/organization.mdx?collection=docs"), "advanced/rules-engine.mdx": () => import("../content/docs/advanced/rules-engine.mdx?collection=docs"), "basics/device-control.mdx": () => import("../content/docs/basics/device-control.mdx?collection=docs"), "basics/groups-zones.mdx": () => import("../content/docs/basics/groups-zones.mdx?collection=docs"), "basics/menu-bar.mdx": () => import("../content/docs/basics/menu-bar.mdx?collection=docs"), "basics/studio-window.mdx": () => import("../content/docs/basics/studio-window.mdx?collection=docs"), "integration/automation-examples.mdx": () => import("../content/docs/integration/automation-examples.mdx?collection=docs"), "integration/shortcuts-app.mdx": () => import("../content/docs/integration/shortcuts-app.mdx?collection=docs"), "features/lights.mdx": () => import("../content/docs/features/lights.mdx?collection=docs"), "features/motion-sensors.mdx": () => import("../content/docs/features/motion-sensors.mdx?collection=docs"), "features/scenes.mdx": () => import("../content/docs/features/scenes.mdx?collection=docs"), "features/smart-plugs.mdx": () => import("../content/docs/features/smart-plugs.mdx?collection=docs"), "features/status-sensors.mdx": () => import("../content/docs/features/status-sensors.mdx?collection=docs"), "features/switches.mdx": () => import("../content/docs/features/switches.mdx?collection=docs"), "reference/api-versions.mdx": () => import("../content/docs/reference/api-versions.mdx?collection=docs"), "reference/supported-devices.mdx": () => import("../content/docs/reference/supported-devices.mdx?collection=docs"), "setup/bridge-discovery.mdx": () => import("../content/docs/setup/bridge-discovery.mdx?collection=docs"), "setup/remote-access.mdx": () => import("../content/docs/setup/remote-access.mdx?collection=docs"), "support/faq.mdx": () => import("../content/docs/support/faq.mdx?collection=docs"), "support/reporting-issues.mdx": () => import("../content/docs/support/reporting-issues.mdx?collection=docs"), "support/troubleshooting.mdx": () => import("../content/docs/support/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;